### ISSUE TITLE
ARM64 bootstrap

### ISSUE THREAD

**Issue by soniccyclone** [ExoKomodo/Daybreak#170]
**Is your feature request related to a problem? Please describe.**
Contributors using ARM64 devices (e.g. Steam Deck, M1 Mac) cannot compile Daybreak.

**Describe the solution you'd like**
ARM64 bootstrap binary.

**Comment by JamesOrson** [comment]
Steam Deck is x86-64-v3 and I have  already used Daybreak on it. Steam Deck can use the existing Linux executable.

The existing Linux executable is specifically a glibc x86-64 binary.
