### ISSUE TITLE
Provide type deduction on bindings

### ISSUE THREAD

**Issue by JamesOrson** [ExoKomodo/daybreak#202]
**Is your feature request related to a problem? Please describe.**
Types should not have to be explicitly written for bindings

**Describe the solution you'd like**
To be able to write bindings like so

```
let x <- 42 ? Generates const int x = 42;
let y <- "hello world" ? Generates const char* y = "hello world";
mut z <- 420.420 ? Generates double z = 420.420;
let numbers <- (generate_primes x) ? Assuming generate primes returns a pointer to a struct called Primes, would generate const Primes* numbers = generate_primes(x);
```

**Additional context**
C functions are not parsed and therefore type information is not yet available. C functions will not be able to support type-deduced bindings.

To get type deduction of a C function, you can write a Daybreak wrapper that simply calls the C function and passes the parameters. The daybreak function will provide the type info and due to inline-by-default semantics in Daybreak, the indirection will be lost in compilation and no performance penalty will be incurred. These daybreak wrappers can also provide a more modern and clean interface to the C functions they expose.

**Comment by brandonapol** [comment]
Do you want them all to translate to const or not? Seeing mixed results here

**Comment by JamesOrson** [comment]
C wrapper would look like so and would provide the required type info at the code generation step. Example is of wrapping "fputs"
```
fun fput_string(output_file: ptr<FILE> str: ccstring) int do
  (fputs output_file str)
end
```

**Comment by JamesOrson** [comment]
> Do you want them all to translate to const or not? Seeing mixed results here

The whole point of mut bindings is to provide a non-const binding for C interop

It's a different keyword so it brings attention and can be sought out if it is producing code smells

Because you can't reassign a variable syntactically in daybreak, the risk is low and the keyword functions as a necessity for wrapping some low-level C libraries directly with daybreak.
